# Generated by Django 5.2.1 on 2025-05-08 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AutonomiaMedicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autonomia_gestao', models.CharField(blank=True, choices=[('sem_assistencia', 'Toma medicamento sem assistência'), ('assistencia_lembrete', 'Necessita de lembretes ou de assistência'), ('incapaz', 'Incapaz de tomar sozinho'), ('outro', 'Outro')], max_length=30, null=True, verbose_name='Autonomia na gestão dos medicamentos')),
                ('autonomia_outro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Outro (quem auxilia com a medicação)')),
                ('dificuldade_tomar', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('outro', 'Outro')], max_length=10, verbose_name='Tem dificuldade para tomar os medicamentos?')),
                ('dificuldade_outro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Outro (qual dificuldade)')),
                ('esquecimentos', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='Já esqueceu de tomar os medicamentos?')),
                ('toma_no_horario', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Toma os medicamentos no horário indicado?')),
                ('interrompe_quando_bem', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Quando se sente bem, deixa de tomar?')),
                ('interrompe_quando_mal', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Quando se sente mal, deixa de tomar?')),
                ('desconforto_medicamento', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('outro', 'Outro')], max_length=10, verbose_name='Sente algum desconforto com os medicamentos?')),
                ('desconforto_outro', models.TextField(blank=True, null=True, verbose_name='Descreva o desconforto e o medicamento')),
                ('uso_alternativos', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('outro', 'Outro')], max_length=10, verbose_name='Faz uso de chás ou terapias alternativas?')),
                ('uso_alternativos_outro', models.TextField(blank=True, null=True, verbose_name='Descreva quais')),
                ('local_guarda', models.CharField(choices=[('cozinha_banheiro', 'Cozinha/Banheiro'), ('quarto_sala', 'Quarto/Sala'), ('copa', 'Copa'), ('gavetas', 'Em Gavetas'), ('caixas', 'Em Caixas'), ('cartelas', 'Cartelas soltas'), ('geladeira', 'Geladeira'), ('armarios', 'Armários')], max_length=30, verbose_name='Onde guarda os medicamentos em casa?')),
                ('forma_descarte', models.CharField(choices=[('lixo_comum', 'Lixo Comum'), ('vaso_sanitario', 'Joga no Vaso Sanitário'), ('queima', 'Queima'), ('enterra', 'Enterra no solo'), ('outro', 'Outro')], max_length=30, verbose_name='Como descarta os medicamentos vencidos?')),
                ('forma_descarte_outro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Outro (forma de descarte)')),
                ('pressao_arterial', models.CharField(blank=True, max_length=15, null=True, verbose_name='Pressão Arterial')),
                ('frequencia_cardiaca', models.CharField(blank=True, max_length=10, null=True, verbose_name='Frequência Cardíaca')),
                ('glicemia', models.CharField(blank=True, max_length=10, null=True, verbose_name='Glicemia')),
                ('observacoes_importantes', models.TextField(blank=True, null=True, verbose_name='Observações Importantes')),
                ('anamnese', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autonomia', to='paciente.anamnese')),
            ],
        ),
        migrations.CreateModel(
            name='HabitosAlimentares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_acorda', models.TimeField(blank=True, null=True)),
                ('cafe_da_manha', models.TextField(blank=True)),
                ('lanche_manha', models.TextField(blank=True)),
                ('almoco', models.TextField(blank=True)),
                ('lanche_tarde', models.TextField(blank=True)),
                ('jantar', models.TextField(blank=True)),
                ('horario_dorme', models.TimeField(blank=True, null=True)),
                ('ultima_refeicao', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('anamnese', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to='paciente.anamnese')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consome_bebida', models.CharField(choices=[('nao', 'Não'), ('sim', 'Sim')], max_length=3)),
                ('tipos_bebidas', models.CharField(blank=True, choices=[('fermentadas', 'Bebidas Fermentadas'), ('mistas', 'Bebidas Mistas'), ('destiladas', 'Bebidas Destiladas')], max_length=20)),
                ('quantidade_ingerida', models.CharField(blank=True, choices=[('1_a_3', '1 a 3 copos'), ('4_a_6', '4 a 6 copos'), ('7_a_9', '7 a 9 copos'), ('acima_de_10', 'Acima de 10 copos'), ('nao_informou', 'Não informou')], max_length=20)),
                ('frequencia_uso', models.CharField(blank=True, choices=[('todos_os_dias', 'Todos os dias'), ('todo_final_de_semana', 'Todo final de semana'), ('1_vez_ao_mes', '1 vez ao mês'), ('a_cada_3_meses', 'A cada 3 meses'), ('raramente', 'Raramente')], max_length=20)),
                ('fumante', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('parou', 'Fumava, mas parou'), ('fumante_passivo', 'Fumante passivo'), ('outro', 'Outro')], max_length=20)),
                ('tempo_parou', models.IntegerField(blank=True, null=True)),
                ('tempo_fumou', models.IntegerField(blank=True, null=True)),
                ('pratica_atividade_fisica', models.BooleanField(default=False)),
                ('atividades_fisicas', models.CharField(blank=True, max_length=20)),
                ('frequencia_atividade', models.CharField(blank=True, max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('anamnese', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia', to='paciente.anamnese')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentoDoencaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('anamnese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_doenca', to='paciente.anamnese')),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.doenca')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=15)),
                ('responsavel', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('ND', 'Prefere não dizer')], max_length=15)),
                ('estado_civil', models.CharField(choices=[('Casado(a)', 'Casado(a)'), ('Solteiro(a)', 'Solteiro(a)'), ('Separado(a)', 'Separado(a)'), ('Amigado(a)', 'Amigado(a)'), ('Viuvo(a)', 'Viúvo(a)'), ('Nao consta', 'Não consta'), ('Outro', 'Outro')], max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('distrito', models.CharField(choices=[('Rural', 'Zona Rural'), ('Urbano', 'Zona Urbana')], max_length=20)),
                ('municipio', models.CharField(max_length=100)),
                ('escolaridade', models.CharField(choices=[('Analfabeto', 'Analfabeto'), ('Fundamental incompleto', 'Fundamental incompleto'), ('Fundamental completo', 'Fundamental completo'), ('Médio incompleto', 'Médio incompleto'), ('Ensino médio completo', 'Ensino médio completo'), ('Superior incompleto', 'Superior incompleto'), ('Superior completo', 'Superior completo'), ('Pós-graduação', 'Pós-graduação'), ('Nao consta', 'Não consta')], max_length=30)),
                ('ocupacao', models.CharField(max_length=100)),
                ('raca', models.CharField(choices=[('Pardo', 'Pardo'), ('Preto', 'Preto'), ('Branco', 'Branco'), ('Amarelo', 'Amarelo'), ('Negro', 'Negro'), ('Outro', 'Outro'), ('Nao consta', 'Não consta')], max_length=20)),
                ('reside_com', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('doencas', models.ManyToManyField(blank=True, related_name='pacientes', through='paciente.MedicamentoDoencaPaciente', to='paciente.doenca')),
                ('medicamentos', models.ManyToManyField(blank=True, related_name='pacientes', to='paciente.medicamento')),
            ],
        ),
        migrations.AddField(
            model_name='medicamentodoencapaciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_doenca_paciente', to='paciente.paciente'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to='paciente.paciente'),
        ),
        migrations.CreateModel(
            name='PerfilClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidade_atividade', models.CharField(blank=True, max_length=50)),
                ('incomodo', models.CharField(blank=True, max_length=100, null=True)),
                ('ultima_visita_dentista', models.DateField(blank=True, null=True)),
                ('percepcao_saude', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('anamnese', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='paciente.anamnese')),
            ],
        ),
        migrations.CreateModel(
            name='Saude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomodo', models.CharField(blank=True, choices=[('dor', 'Dor'), ('queixas', 'Queixas'), ('angustias', 'Angústias'), ('sono', 'Sono'), ('outro', 'Outro')], max_length=100, null=True, verbose_name='O senhor(a) sente algo que lhe incomoda? (dor, queixas, angústias, sono)')),
                ('informacoes_importantes', models.TextField(blank=True, null=True, verbose_name='Informações importantes: (Alergias, Quedas, Cirurgias)')),
                ('ultima_visita_dentista', models.DateField(blank=True, null=True, verbose_name='Última vez que foi ao dentista')),
                ('percepcao_saude', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='PERCEPÇÃO GERAL DA SAÚDE (0-10)')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Por quê?')),
                ('pressao_controlada', models.BooleanField(blank=True, default=False, null=True, verbose_name='Pressão arterial está controlada?')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Importantes:')),
                ('anamnese', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saude', to='paciente.anamnese')),
            ],
        ),
    ]
