# Generated by Django 5.1.1 on 2024-10-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('numero_formulario', models.CharField(max_length=10)),
                ('responsavel', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10)),
                ('estado_civil', models.CharField(choices=[('Casado(a)', 'Casado(a)'), ('Solteiro(a)', 'Solteiro(a)'), ('Separado(a)', 'Separado(a)'), ('Amigado(a)', 'Amigado(a)'), ('Nao consta', 'Não consta'), ('Outro', 'Outro')], max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('distrito', models.CharField(choices=[('Rural', 'Zona Rural'), ('Urbano', 'Zona Urbana')], max_length=20)),
                ('municipio', models.CharField(max_length=100)),
                ('escolaridade', models.CharField(choices=[('Analfabeto', 'Analfabeto'), ('Fundamental incompleto', 'Fundamental incompleto'), ('Fundamental completo', 'Fundamental completo'), ('Médio incompleto', 'Médio incompleto'), ('Ensino médio completo', 'Ensino médio completo'), ('Superior incompleto', 'Superior incompleto'), ('Superior completo', 'Superior completo'), ('Pós-graduação', 'Pós-graduação'), ('Nao consta', 'Não consta')], max_length=30)),
                ('ocupacao', models.CharField(max_length=100)),
                ('raca', models.CharField(choices=[('Pardo', 'Pardo'), ('Preto', 'Preto'), ('Branco', 'Branco'), ('Amarelo', 'Amarelo'), ('Negro', 'Negro'), ('Outro', 'Outro'), ('Nao consta', 'Não consta')], max_length=20)),
                ('reside_com', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('consome_bebida', models.CharField(choices=[('nao', 'Não'), ('sim', 'Sim')], max_length=3)),
                ('tipos_bebidas', models.CharField(blank=True, choices=[('fermentadas', 'Bebidas Fermentadas'), ('mistas', 'Bebidas Mistas'), ('destiladas', 'Bebidas Destiladas')], max_length=20)),
                ('quantidade_ingerida', models.CharField(blank=True, choices=[('1_a_3', '1 a 3 copos'), ('4_a_6', '4 a 6 copos'), ('7_a_9', '7 a 9 copos'), ('acima_de_10', 'Acima de 10 copos'), ('nao_informou', 'Não informou')], max_length=20)),
                ('frequencia_uso', models.CharField(blank=True, choices=[('todos_os_dias', 'Todos os dias'), ('todo_final_de_semana', 'Todo final de semana'), ('1_vez_ao_mes', '1 vez ao mês'), ('a_cada_3_meses', 'A cada 3 meses'), ('raramente', 'Raramente')], max_length=20)),
                ('fumante', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('parou', 'Fumava, mas parou'), ('fumante_passivo', 'Fumante passivo'), ('outro', 'Outro')], max_length=20)),
                ('tempo_parou', models.IntegerField(blank=True, null=True)),
                ('tempo_fumou', models.IntegerField(blank=True, null=True)),
                ('pratica_atividade_fisica', models.BooleanField(default=False)),
                ('atividades_fisicas', models.CharField(blank=True, choices=[('caminhar', 'Caminhar'), ('pedalar', 'Pedalar'), ('danca', 'Dança'), ('praticar_esportes', 'Praticar esportes'), ('fisioterapia', 'Fisioterapia'), ('outro', 'Outro')], max_length=20)),
                ('frequencia_atividade', models.CharField(blank=True, choices=[('todos_os_dias', 'Todos os dias'), ('1_vez_na_semana', '1 vez na semana'), ('2_3_vezes_na_semana', '2 - 3 vezes na semana'), ('4_6_vezes_na_semana', '4 - 6 vezes na semana'), ('outro', 'Outro')], max_length=20)),
                ('duracao_exercicio', models.CharField(blank=True, max_length=100)),
                ('observacoes_historia_social', models.TextField(blank=True)),
                ('horario_acorda', models.TimeField()),
                ('cafe_da_manha', models.TextField()),
                ('lanche_manha', models.TextField()),
                ('almoco', models.TextField()),
                ('lanche_tarde', models.TextField()),
                ('jantar', models.TextField()),
                ('horario_dorme', models.TimeField()),
                ('ultima_refeicao', models.TextField()),
                ('observacoes_habitos_alimentares', models.TextField(blank=True)),
                ('doencas_hereditarias', models.TextField()),
                ('data_conhecimento_doenca', models.DateField()),
                ('quantidade_medicamentos', models.CharField(max_length=10)),
                ('capacidade_atividade', models.CharField(max_length=50)),
                ('observacoes_perfil_clinico', models.TextField(blank=True)),
                ('incomodos', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True)),
                ('ultima_visita_dentista', models.DateField()),
                ('percepcao_saude', models.IntegerField()),
                ('pressao_controlada', models.BooleanField(default=False)),
                ('observacoes_importantes', models.TextField(blank=True)),
                ('assistencia_medicamento', models.CharField(max_length=50)),
                ('dificuldade_tomar', models.CharField(max_length=50)),
                ('esquecimento_medicamentos', models.BooleanField(default=False)),
                ('horario_medicamentos', models.BooleanField(default=False)),
                ('interrompe_quando_bem', models.BooleanField(default=False)),
                ('interrompe_quando_mal', models.BooleanField(default=False)),
                ('desconforto_medicamento', models.TextField(blank=True)),
                ('uso_terapias_alternativas', models.CharField(max_length=50)),
                ('local_armazenamento', models.CharField(max_length=50)),
                ('forma_descarte', models.CharField(max_length=50)),
                ('rastreamento_saude', models.TextField(blank=True)),
            ],
        ),
    ]
