# Generated by Django 5.2 on 2025-04-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autonomiamedicamentos',
            name='paciente',
        ),
    ]
