# Generated by Django 5.2.1 on 2025-05-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilclinico',
            name='percepcao_saude',
        ),
        migrations.RemoveField(
            model_name='perfilclinico',
            name='ultima_visita_dentista',
        ),
    ]
