# Generated by Django 5.1.1 on 2024-10-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='almoco',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cafe_da_manha',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='horario_dorme',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='jantar',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='lanche_manha',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='lanche_tarde',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ultima_refeicao',
            field=models.TextField(blank=True),
        ),
    ]
