# Generated by Django 5.2 on 2025-04-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_remove_autonomiamedicamentos_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autonomiamedicamentos',
            name='esquecimentos',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Já esqueceu de tomar os medicamentos?'),
        ),
    ]
