# Generated by Django 5.1.1 on 2024-10-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_paciente_almoco_alter_paciente_cafe_da_manha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='horario_acorda',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
