# Generated by Django 5.1.1 on 2024-10-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_alter_paciente_horario_acorda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='horario_dorme',
            field=models.TimeField(null=True),
        ),
    ]
