# Generated by Django 5.2 on 2025-04-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_alter_autonomiamedicamentos_esquecimentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autonomiamedicamentos',
            name='toma_no_horario',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Toma os medicamentos no horário indicado?'),
        ),
    ]
