# Generated by Django 5.2.1 on 2025-05-23 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_alter_saude_ultima_visita_dentista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentodoencapaciente',
            name='doenca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.doenca'),
        ),
        migrations.AlterField(
            model_name='medicamentodoencapaciente',
            name='medicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.medicamento'),
        ),
    ]
