# Generated by Django 5.1.1 on 2024-10-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_alter_paciente_horario_dorme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_conhecimento_doenca',
            field=models.DateField(blank=True, null=True),
        ),
    ]
