# Generated by Django 5.2 on 2025-04-04 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_alter_autonomiamedicamentos_esquecimentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='autonomiamedicamentos',
            name='paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autonimia_medicamentos', to='paciente.paciente'),
        ),
        migrations.AlterField(
            model_name='autonomiamedicamentos',
            name='esquecimentos',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='Já esqueceu de tomar os medicamentos?'),
        ),
        migrations.AlterField(
            model_name='autonomiamedicamentos',
            name='toma_no_horario',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True, verbose_name='Toma os medicamentos no horário indicado?'),
        ),
        migrations.AlterField(
            model_name='saude',
            name='pressao_controlada',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Pressão arterial está controlada?'),
        ),
    ]
