# Generated by Django 5.1.1 on 2024-10-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_alter_paciente_data_conhecimento_doenca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='ultima_visita_dentista',
            field=models.DateField(blank=True, null=True),
        ),
    ]
