# Generated by Django 5.1.1 on 2024-10-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_alter_paciente_ultima_visita_dentista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='percepcao_saude',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tempo_fumou',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tempo_parou',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
