# Generated by Django 5.1.1 on 2025-04-06 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_autonomiamedicamentos_paciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfilclinico',
            name='doencas_hereditarias',
        ),
        migrations.RemoveField(
            model_name='perfilclinico',
            name='quantidade_medicamentos',
        ),
        migrations.AlterField(
            model_name='autonomiamedicamentos',
            name='autonomia_gestao',
            field=models.CharField(blank=True, choices=[('sem_assistencia', 'Toma medicamento sem assistência'), ('assistencia_lembrete', 'Necessita de lembretes ou de assistência'), ('incapaz', 'Incapaz de tomar sozinho'), ('outro', 'Outro')], max_length=30, null=True, verbose_name='Autonomia na gestão dos medicamentos'),
        ),
        migrations.AlterField(
            model_name='autonomiamedicamentos',
            name='paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autonomia_medicamentos', to='paciente.paciente'),
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('doenca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='paciente.doenca')),
            ],
        ),
    ]
