# Generated by Django 5.1.1 on 2025-04-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_doenca_remove_perfilclinico_doencas_hereditarias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doenca',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
