# Generated by Django 5.1.1 on 2024-10-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_alter_paciente_percepcao_saude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='data_conhecimento_doenca',
            new_name='desde_quando_conhecimento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='incomodos',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='observacoes_perfil_clinico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='percepcao_saude',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='pressao_controlada',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='ultima_visita_dentista',
        ),
        migrations.AddField(
            model_name='paciente',
            name='outro_doenca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='capacidade_atividade',
            field=models.CharField(blank=True, choices=[('excelente', 'Excelente capacidade'), ('boa', 'Boa capacidade'), ('moderada', 'Capacidade moderada'), ('comprometimento_grave', 'Comprometimento grave da capacidade'), ('total_comprometimento', 'Total comprometimento de capacidade')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='doencas_hereditarias',
            field=models.CharField(blank=True, choices=[('hipertensao', 'Hipertensão'), ('diabetes', 'Diabetes'), ('dislipidemia', 'Dislipidemia (Colesterol Alto)'), ('doencas_cardiacas', 'Doenças Cardíacas'), ('dpo', 'Doença pulmonar obstrutiva crônica (DPOC)'), ('asma', 'Asma'), ('depressao_ansiedade', 'Depressão/Ansiedade'), ('avc', 'AVC'), ('osteoartrite', 'Osteoartrite'), ('fibromialgia', 'Fibromialgia'), ('outro', 'Outro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='quantidade_medicamentos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
