# Generated by Django 5.1.1 on 2025-04-06 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_alter_doenca_nome_alter_medicamento_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='doenca',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doencas', to='paciente.paciente'),
        ),
    ]
