# Generated by Django 5.1.1 on 2025-04-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_doenca_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doenca',
            name='paciente',
        ),
        migrations.AddField(
            model_name='paciente',
            name='doencas',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to='paciente.doenca'),
        ),
    ]
