# Generated by Django 5.1.1 on 2024-10-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_paciente_incomodo_paciente_informacoes_importantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tempo_fumou',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tempo_parou',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
