# Generated by Django 5.1.1 on 2025-04-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0010_remove_doenca_paciente_paciente_doencas'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='medicamentos',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to='paciente.medicamento'),
        ),
    ]
