# Generated by Django 5.1.1 on 2025-03-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0011_doenca_medicamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doenca',
        ),
        migrations.DeleteModel(
            name='Medicamento',
        ),
    ]
