# Generated by Django 5.1.1 on 2025-04-06 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0011_paciente_medicamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='doenca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='paciente.doenca'),
            preserve_default=False,
        ),
    ]
