# Generated by Django 5.1.1 on 2025-03-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_delete_doenca_delete_medicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problema_Saude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicamentos',
            field=models.ManyToManyField(blank=True, to='paciente.medicamentos'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='problemas_saude',
            field=models.ManyToManyField(blank=True, to='paciente.problema_saude'),
        ),
    ]
