# Generated by Django 5.1.1 on 2025-04-06 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_alter_medicamento_doenca'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoDoencaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.doenca')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_doenca_paciente', to='paciente.paciente')),
            ],
        ),
    ]
