# Generated by Django 5.1.1 on 2025-03-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0013_medicamentos_problema_saude_paciente_medicamentos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='outro_doenca',
        ),
        migrations.AddField(
            model_name='paciente',
            name='outra_doenca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='incomodo',
            field=models.CharField(blank=True, choices=[('dor', 'Dor'), ('queixas', 'Queixas'), ('angustias', 'Angústias'), ('sono', 'Sono'), ('outro', 'Outro')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='informacoes_importantes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='justificativa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='percepcao_saude',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pressao_controlada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ultima_visita_dentista',
            field=models.DateField(blank=True, null=True),
        ),
    ]
