# Generated by Django 5.1.1 on 2025-03-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0014_remove_paciente_outro_doenca_paciente_outra_doenca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='medicamentos',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='problemas_saude',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='outra_doenca',
        ),
        migrations.AddField(
            model_name='paciente',
            name='outro_doenca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='incomodo',
            field=models.CharField(blank=True, choices=[('dor', 'Dor'), ('queixas', 'Queixas'), ('angustias', 'Angústias'), ('sono', 'Sono'), ('outro', 'Outro')], max_length=100, null=True, verbose_name='O senhor(a) sente algo que lhe incomoda? (dor, queixas, angústias, sono)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='informacoes_importantes',
            field=models.TextField(blank=True, null=True, verbose_name='Informações importantes: (Alergias, Quedas, Cirurgias)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='justificativa',
            field=models.TextField(blank=True, null=True, verbose_name='Por quê?'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Importantes:'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='percepcao_saude',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='PERCEPÇÃO GERAL DA SAÚDE (0-10)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pressao_controlada',
            field=models.BooleanField(default=False, verbose_name='Pressão arterial está controlada?'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ultima_visita_dentista',
            field=models.DateField(blank=True, null=True, verbose_name='Última vez que foi ao dentista'),
        ),
        migrations.DeleteModel(
            name='Medicamentos',
        ),
        migrations.DeleteModel(
            name='Problema_Saude',
        ),
    ]
