# Generated by Django 5.1.1 on 2025-03-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0015_remove_paciente_medicamentos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='outro_doenca',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
