# Generated by Django 5.1.1 on 2025-03-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0016_alter_paciente_outro_doenca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='outro_doenca',
            new_name='outra_doenca',
        ),
    ]
