# Generated by Django 5.1.1 on 2025-03-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0017_rename_outro_doenca_paciente_outra_doenca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='outra_doenca',
        ),
    ]
