# Generated by Django 5.1.1 on 2025-03-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0018_remove_paciente_outra_doenca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='doencas_paciente',
            field=models.ManyToManyField(blank=True, to='paciente.doenca'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicamentos_paciente',
            field=models.ManyToManyField(blank=True, to='paciente.medicamento'),
        ),
    ]
