# Generated by Django 5.1.1 on 2025-03-20 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0019_doenca_medicamento_paciente_doencas_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='doencas_paciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medicamentos_paciente',
        ),
        migrations.AddField(
            model_name='doenca',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doencas', to='paciente.paciente'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='paciente.paciente'),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='assistencia_medicamento',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dificuldade_tomar',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='forma_descarte',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('ND', 'Prefere não dizer')], max_length=15),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='local_armazenamento',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='uso_terapias_alternativas',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
