# Generated by Django 5.1.1 on 2025-04-01 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0020_remove_paciente_doencas_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doenca',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doencas', to='paciente.paciente'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='paciente.paciente'),
        ),
    ]
