# Generated by Django 5.1.1 on 2025-04-03 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0021_alter_doenca_paciente_alter_medicamento_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='paciente',
        ),
        migrations.CreateModel(
            name='DoencaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('controlada', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doencas_paciente', to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('uso_continuo', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_paciente', to='paciente.paciente')),
            ],
        ),
        migrations.DeleteModel(
            name='Doenca',
        ),
        migrations.DeleteModel(
            name='Medicamento',
        ),
    ]
