# Generated by Django 5.1.1 on 2025-04-28 15:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(
                    max_length=150,
                    unique=True,
                    validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                    error_messages={'unique': 'A user with that username already exists.'},
                    help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                    verbose_name='username'
                )),
                ('first_name', models.CharField(max_length=150, blank=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, blank=True, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, blank=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status', help_text='Designates whether the user can log into this admin site.')),
                ('is_active', models.BooleanField(default=True, verbose_name='active', help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),

                # O campo novo para seu projeto:
                ('tipo_usuario', models.CharField(
                    max_length=20,
                    choices=[
                        ('farmaceutico', 'Farmacêutico'),
                        ('aluno', 'Aluno'),
                        ('convidado', 'Convidado'),
                    ],
                    default='convidado'
                )),

                # ManyToManyFields para permissões e grupos
                ('groups', models.ManyToManyField(
                    to='auth.group',
                    blank=True,
                    related_name='user_set',
                    related_query_name='user',
                    verbose_name='groups',
                    help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.'
                )),
                ('user_permissions', models.ManyToManyField(
                    to='auth.permission',
                    blank=True,
                    related_name='user_set',
                    related_query_name='user',
                    verbose_name='user permissions',
                    help_text='Specific permissions for this user.'
                )),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
