# Generated by Django 5.1.1 on 2025-04-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('farmaceutico', 'Farmacêutico'), ('aluno', 'Aluno'), ('convidado', 'Convidado')], default='farmaceutico', max_length=20),
        ),
    ]
