# Generated by Django 5.1.1 on 2025-04-28 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_logatividade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logatividade',
            options={'ordering': ['-data_hora']},
        ),
    ]
