# Generated by Django 5.2.1 on 2025-05-08 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('evolucao', models.TextField()),
                ('motivo_consulta', models.TextField(max_length=255)),
                ('prescricoes_exames', models.TextField()),
                ('data_proxima_revisao', models.DateField()),
                ('exames_arquivo', models.FileField(blank=True, null=True, upload_to='exames_consulta/', verbose_name='Arquivo de Exames (PDF, JPG, PNG, DOC etc.)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=255)),
                ('desde', models.DateField()),
                ('prescrita', models.CharField(max_length=255)),
                ('utilizada', models.CharField(max_length=255)),
                ('para_que_servir', models.TextField()),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='consulta.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necessidade', models.BooleanField(default=False)),
                ('efetividade', models.BooleanField(default=False)),
                ('seguranca', models.BooleanField(default=False)),
                ('classificacao_rnm_1', models.CharField(choices=[('PSNT', 'Problema de saúde não tratado'), ('EMD', 'Efeito de medicamento desnecessário'), ('INQ', 'Inefetividade não quantitativa'), ('IQ', 'Inefetividade quantitativa'), ('ISQ', 'Insegurança quantitativa')], max_length=50)),
                ('classificacao_rnm_2', models.CharField(choices=[('PSNT', 'Problema de saúde não tratado'), ('EMD', 'Efeito de medicamento desnecessário'), ('INQ', 'Inefetividade não quantitativa'), ('IQ', 'Inefetividade quantitativa'), ('ISQ', 'Insegurança quantitativa'), ('NC', 'Não consta')], max_length=50)),
                ('situacao_problema_saude', models.CharField(choices=[('PM', 'Problema manifestado'), ('RA', 'Risco de aparecimento')], max_length=50)),
                ('causa_rnm', models.TextField()),
                ('medicamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='consulta.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivos', models.TextField()),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=20)),
                ('registro_intervencao', models.CharField(choices=[('quantidade_medicamento', 'Intervir na quantidade de medicamento'), ('estrategia_farmacologica', 'Intervir na estratégia farmacológica'), ('educacao_paciente', 'Intervir na educação do paciente')], max_length=50)),
                ('classificacao_intervencao', models.CharField(choices=[('modificar_dose', 'Modificar a dose'), ('modificar_dosagem', 'Modificar a dosagem'), ('modificar_esquema', 'Modificar o esquema terapêutico'), ('adicionar_medicamento', 'Adicionar medicamento'), ('retirar_medicamento', 'Retirar medicamento'), ('substituir_medicamento', 'Substituir medicamento'), ('modo_uso', 'Modo de uso e administração'), ('aumentar_adesao', 'Aumentar a adesão ao tratamento'), ('educar_nao_farmacologico', 'Educar em medidas não farmacológicas'), ('nao_claro', 'Não está claro')], max_length=50)),
                ('descricao_planejamento', models.TextField(blank=True, null=True)),
                ('data_intervencao', models.DateField()),
                ('alcancado', models.BooleanField(default=False)),
                ('data_alcancado', models.DateField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True)),
                ('rnm_resolvido', models.BooleanField(default=False)),
                ('o_que_aconteceu', models.TextField(blank=True, null=True)),
                ('avaliacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_atuacao', to='consulta.avaliacao')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_de_atuacao', to='consulta.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.CharField(max_length=255)),
                ('inicio', models.DateField()),
                ('controlado', models.BooleanField(default=False)),
                ('preocupa', models.BooleanField(default=False)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemas_saude', to='consulta.consulta')),
            ],
        ),
        migrations.AddField(
            model_name='medicamento',
            name='problema_saude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='consulta.problemasaude'),
        ),
    ]
