# Generated by Django 5.2 on 2025-04-04 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('evolucao', models.TextField()),
                ('motivo_consulta', models.TextField(max_length=255)),
                ('prescricoes_exames', models.TextField()),
                ('data_proxima_revisao', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.BooleanField(default=False)),
                ('e', models.BooleanField(default=False)),
                ('s', models.BooleanField(default=False)),
                ('classificacao_rnm_1', models.CharField(max_length=255)),
                ('classificacao_rnm_2', models.CharField(max_length=255)),
                ('situacao_problema_saude', models.CharField(max_length=255)),
                ('causa_rnm', models.TextField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='consulta.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=255)),
                ('desde', models.DateField()),
                ('prescrita', models.BooleanField(default=False)),
                ('utilizada', models.BooleanField(default=False)),
                ('para_que_servir', models.TextField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='consulta.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivos', models.TextField()),
                ('prioridade', models.CharField(max_length=255)),
                ('registro_intervencao', models.TextField()),
                ('classificacao_intervencao', models.CharField(max_length=255)),
                ('descricao_planejamento', models.TextField()),
                ('data_intervencao', models.DateField()),
                ('alcançado', models.BooleanField(default=False)),
                ('data_alcancado', models.DateField(blank=True, null=True)),
                ('resultado', models.TextField()),
                ('rnm_resolvido', models.BooleanField(default=False)),
                ('o_que_aconteceu', models.TextField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_de_atuacao', to='consulta.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.CharField(max_length=255)),
                ('inicio', models.DateField()),
                ('controlado', models.BooleanField(default=False)),
                ('preocupa', models.BooleanField(default=False)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemas_saude', to='consulta.consulta')),
            ],
        ),
    ]
