# Generated by Django 5.1.1 on 2024-10-14 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0009_paciente_incomodo_paciente_informacoes_importantes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('evolucao', models.TextField()),
                ('motivo_consulta', models.CharField(max_length=255)),
                ('prescricoes_exames', models.TextField()),
                ('data_proxima_revisao', models.DateField()),
                ('problema_saude', models.CharField(max_length=255)),
                ('inicio', models.DateField()),
                ('controlado', models.BooleanField(default=False)),
                ('preocupa', models.BooleanField(default=False)),
                ('medicamento', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=255)),
                ('desde', models.DateField()),
                ('prescrita', models.BooleanField(default=False)),
                ('utilizada', models.BooleanField(default=False)),
                ('para_que_servir', models.TextField()),
                ('n', models.BooleanField(default=False)),
                ('e', models.BooleanField(default=False)),
                ('s', models.BooleanField(default=False)),
                ('classificacao_rnm_1', models.CharField(max_length=255)),
                ('classificacao_rnm_2', models.CharField(max_length=255)),
                ('situacao_problema_saude', models.CharField(max_length=255)),
                ('causa_rnm', models.TextField()),
                ('objetivos', models.TextField()),
                ('prioridade', models.CharField(max_length=255)),
                ('registro_intervencao', models.TextField()),
                ('classificacao_intervencao', models.CharField(max_length=255)),
                ('descricao_planejamento', models.TextField()),
                ('data_intervencao', models.DateField()),
                ('alcançado', models.BooleanField(default=False)),
                ('data_alcancado', models.DateField(blank=True, null=True)),
                ('resultado', models.TextField()),
                ('rnm_resolvido', models.BooleanField(default=False)),
                ('o_que_aconteceu', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='paciente.paciente')),
            ],
        ),
    ]
