# Generated by Django 5.2.1 on 2025-05-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_proxima_revisao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
