# Generated by Django 5.1.1 on 2025-04-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planoatuacao',
            old_name='alcançado',
            new_name='alcancado',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='classificacao_rnm_1',
            field=models.CharField(choices=[('PSNT', 'Problema de saúde não tratado'), ('EMD', 'Efeito de medicamento desnecessário'), ('INQ', 'Inefetividade não quantitativa'), ('IQ', 'Inefetividade quantitativa'), ('INNQ', 'Insegurança não quantitativa'), ('INQ', 'Insegurança quantitativa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='classificacao_rnm_2',
            field=models.CharField(choices=[('PSNT', 'Problema de saúde não tratado'), ('EMD', 'Efeito de medicamento desnecessário'), ('INQ', 'Inefetividade não quantitativa'), ('IQ', 'Inefetividade quantitativa'), ('INNQ', 'Insegurança não quantitativa'), ('INQ', 'Insegurança quantitativa'), ('NC', 'Não consta')], max_length=50),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='situacao_problema_saude',
            field=models.CharField(choices=[('PM', 'Problema manifestado'), ('RA', 'Risco de aparecimento')], max_length=50),
        ),
        migrations.AlterField(
            model_name='planoatuacao',
            name='classificacao_intervencao',
            field=models.CharField(choices=[('modificar_dose', 'Modificar a dose'), ('modificar_dosagem', 'Modificar a dosagem'), ('modificar_esquema', 'Modificar o esquema terapêutico'), ('adicionar_medicamento', 'Adicionar medicamento'), ('retirar_medicamento', 'Retirar medicamento'), ('substituir_medicamento', 'Substituir medicamento'), ('modo_uso', 'Modo de uso e administração'), ('aumentar_adesao', 'Aumentar a adesão ao tratamento'), ('educar_nao_farmacologico', 'Educar em medidas não farmacológicas'), ('nao_claro', 'Não está claro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='planoatuacao',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='planoatuacao',
            name='registro_intervencao',
            field=models.CharField(choices=[('quantidade_medicamento', 'Intervir na quantidade de medicamento'), ('estrategia_farmacologica', 'Intervir na estratégia farmacológica'), ('educacao_paciente', 'Intervir na educação do paciente')], max_length=50),
        ),
    ]
