# Generated by Django 5.2.1 on 2025-05-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_alter_consulta_data_proxima_revisao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='para_que_servir',
            new_name='entendimento_paciente',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='prescrita',
            new_name='posologia_prescrita',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='utilizada',
            new_name='posologia_utilizada',
        ),
    ]
