# Generated by Django 5.1.1 on 2024-10-14 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_alter_consulta_motivo_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='alcançado',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='causa_rnm',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='classificacao_intervencao',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='classificacao_rnm_1',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='classificacao_rnm_2',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='controlado',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='data_alcancado',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='data_intervencao',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='descricao_planejamento',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='desde',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='e',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='medicamento',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='n',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='o_que_aconteceu',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='objetivos',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='para_que_servir',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='preocupa',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='prescrita',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='prioridade',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='problema_saude',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='registro_intervencao',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='rnm_resolvido',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='s',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='situacao_problema_saude',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='utilizada',
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.BooleanField(default=False)),
                ('e', models.BooleanField(default=False)),
                ('s', models.BooleanField(default=False)),
                ('classificacao_rnm_1', models.CharField(max_length=255)),
                ('classificacao_rnm_2', models.CharField(max_length=255)),
                ('situacao_problema_saude', models.CharField(max_length=255)),
                ('causa_rnm', models.TextField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='consulta.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=255)),
                ('desde', models.DateField()),
                ('prescrita', models.BooleanField(default=False)),
                ('utilizada', models.BooleanField(default=False)),
                ('para_que_servir', models.TextField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='consulta.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivos', models.TextField()),
                ('prioridade', models.CharField(max_length=255)),
                ('registro_intervencao', models.TextField()),
                ('classificacao_intervencao', models.CharField(max_length=255)),
                ('descricao_planejamento', models.TextField()),
                ('data_intervencao', models.DateField()),
                ('alcançado', models.BooleanField(default=False)),
                ('data_alcancado', models.DateField(blank=True, null=True)),
                ('resultado', models.TextField()),
                ('rnm_resolvido', models.BooleanField(default=False)),
                ('o_que_aconteceu', models.TextField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_de_atuacao', to='consulta.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.CharField(max_length=255)),
                ('inicio', models.DateField()),
                ('controlado', models.BooleanField(default=False)),
                ('preocupa', models.BooleanField(default=False)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemas_de_saude', to='consulta.consulta')),
            ],
        ),
    ]
