# Generated by Django 5.1.1 on 2025-04-08 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_rename_e_avaliacao_efetividade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='consulta',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='medicamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='consulta.medicamento'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='problema_saude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='consulta.problemasaude'),
        ),
    ]
