# Generated by Django 5.1.1 on 2025-03-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_remove_consulta_alcançado_remove_consulta_causa_rnm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='consulta',
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='classe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='para_que_servir',
            field=models.TextField(blank=True, null=True),
        ),
    ]
