# Generated by Django 5.2.1 on 2025-05-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_rename_para_que_servir_medicamento_entendimento_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planoatuacao',
            name='alcancado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='planoatuacao',
            name='rnm_resolvido',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
