# Generated by Django 5.2.1 on 2025-05-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_alter_medicamento_desde_alter_planoatuacao_alcancado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoatuacao',
            name='alcancado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planoatuacao',
            name='rnm_resolvido',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
