# Generated by Django 5.1.1 on 2025-03-19 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_remove_medicamento_consulta_alter_medicamento_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='consulta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='consulta.consulta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='classe',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='desde',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='para_que_servir',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
