# Generated by Django 5.2.1 on 2025-05-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0005_alter_planoatuacao_alcancado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='classe',
            field=models.CharField(blank=True, default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='entendimento_paciente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nome',
            field=models.CharField(blank=True, default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='posologia_prescrita',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='posologia_utilizada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
