# Generated by Django 5.1.1 on 2025-03-19 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0005_medicamento_consulta_alter_medicamento_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemasaude',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemas_saude', to='consulta.consulta'),
        ),
    ]
