# Generated by Django 5.1.1 on 2025-04-09 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0005_medicamento_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='consulta.consulta'),
        ),
    ]
