# Generated by Django 5.2.1 on 2025-05-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0007_alter_avaliacao_causa_rnm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='classe',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nome',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
