# Generated by Django 5.1.1 on 2025-04-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0008_alter_problemasaude_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='prescrita',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='utilizada',
            field=models.CharField(max_length=255),
        ),
    ]
