# Generated by Django 5.2.1 on 2025-05-22 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0008_alter_medicamento_classe_alter_medicamento_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='parametro',
            field=models.CharField(blank=True, choices=[('SS', 'Sinais e Sintomas'), ('SUB', 'Subjetivo'), ('LAB', 'Laboratorial')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='resultado_do_parametro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planoatuacao',
            name='medicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_atuacao', to='consulta.medicamento'),
        ),
        migrations.AddField(
            model_name='planoatuacao',
            name='problema_saude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_atuacao', to='consulta.problemasaude'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='classificacao_rnm_1',
            field=models.CharField(blank=True, choices=[('PSNT', 'Problema de saúde não tratado'), ('EMD', 'Efeito de medicamento desnecessário'), ('INQ', 'Inefetividade não quantitativa'), ('IQ', 'Inefetividade quantitativa'), ('ISQ', 'Insegurança quantitativa'), ('NC', 'Não consta')], default='NC', max_length=50),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='situacao_problema_saude',
            field=models.CharField(blank=True, choices=[('PM', 'Problema manifestado'), ('RA', 'Risco de aparecimento'), ('NC', 'Não consta')], default='NC', max_length=50),
        ),
    ]
