# Generated by Django 5.1.1 on 2025-05-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0009_alter_medicamento_prescrita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='exames_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='exames/', verbose_name='Arquivo de Exames (PDF, JPG, PNG, DOC etc.)'),
        ),
    ]
