# Generated by Django 5.2.1 on 2025-05-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0009_avaliacao_parametro_avaliacao_resultado_do_parametro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemasaude',
            name='inicio',
            field=models.CharField(choices=[('<1M', 'Menos de 1 mês'), ('1-3M', 'De 1 a 3 meses'), ('3-6M', 'De 3 a 6 meses'), ('6M-1A', 'De 6 meses a 1 ano'), ('1-3A', 'De 1 a 3 anos'), ('3-5A', 'De 3 a 5 anos'), ('5-10A', 'De 5 a 10 anos'), ('>10A', 'Mais de 10 anos')], max_length=10),
        ),
    ]
