# Generated by Django 5.1.1 on 2025-05-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0010_consulta_exames_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='exames_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='exames_consulta/', verbose_name='Arquivo de Exames (PDF, JPG, PNG, DOC etc.)'),
        ),
    ]
