# Generated by Django 5.2.1 on 2025-05-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0011_alter_medicamento_desde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='classificacao_rnm_1',
            field=models.CharField(blank=True, choices=[('PSNT', 'Problema de saúde não tratado'), ('EMD', 'Efeito de medicamento desnecessário'), ('INQ', 'Inefetividade não quantitativa'), ('IQ', 'Inefetividade quantitativa'), ('ISQ', 'Insegurança quantitativa'), ('NC', 'Não consta')], default='NC', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='classificacao_rnm_2',
            field=models.CharField(blank=True, choices=[('PSNT', 'Problema de saúde não tratado'), ('EMD', 'Efeito de medicamento desnecessário'), ('INQ', 'Inefetividade não quantitativa'), ('IQ', 'Inefetividade quantitativa'), ('ISQ', 'Insegurança quantitativa'), ('NC', 'Não consta')], default='NC', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='situacao_problema_saude',
            field=models.CharField(blank=True, choices=[('PM', 'Problema manifestado'), ('RA', 'Risco de aparecimento'), ('NC', 'Não consta')], default='NC', max_length=50, null=True),
        ),
    ]
