# Generated by Django 5.2.1 on 2025-05-23 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0013_alter_avaliacao_classificacao_rnm_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatorExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='planoatuacao',
            name='fator_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_atuacao', to='consulta.fatorexterno'),
        ),
    ]
