# Generated by Django 5.2.1 on 2025-05-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0014_fatorexterno_planoatuacao_fator_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoatuacao',
            name='fator_externo',
            field=models.CharField(blank=True, help_text='Caso o fator externo seja selecionado, descreva o fator (ex: Encaminhamento ao Nutricionista).', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='FatorExterno',
        ),
    ]
