# Generated by Django 5.2.1 on 2025-05-23 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0015_alter_planoatuacao_fator_externo_delete_fatorexterno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planoatuacao',
            name='fator_externo',
        ),
        migrations.AddField(
            model_name='planoatuacao',
            name='relato_anamnese',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planoatuacao',
            name='medicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_atuacao', to='consulta.medicamento'),
        ),
        migrations.AlterField(
            model_name='planoatuacao',
            name='problema_saude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_atuacao', to='consulta.problemasaude'),
        ),
    ]
